// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBJRW74zOB_8NYZgBLkG8_Yn7lTd1dgs',
    appId: '1:612115892689:web:8c59bb479eec42f00f78f0',
    messagingSenderId: '612115892689',
    projectId: 'haksik-e3b46',
    authDomain: 'haksik-e3b46.firebaseapp.com',
    storageBucket: 'haksik-e3b46.appspot.com',
    measurementId: 'G-D3YZW14ZPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGy5ndUfIHy5Pp0ibCUhW-hxyhEanEYqc',
    appId: '1:612115892689:android:0e3e999dfef3b1e70f78f0',
    messagingSenderId: '612115892689',
    projectId: 'haksik-e3b46',
    storageBucket: 'haksik-e3b46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRp0KBr9y143ybdbNiq4LoCZ9FR3oftX4',
    appId: '1:612115892689:ios:0fc05c5bd0f5fb240f78f0',
    messagingSenderId: '612115892689',
    projectId: 'haksik-e3b46',
    storageBucket: 'haksik-e3b46.appspot.com',
    iosClientId:
        '612115892689-qn4q4pl3i015mm86avutnj2luuhpbp2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyamNyamFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRp0KBr9y143ybdbNiq4LoCZ9FR3oftX4',
    appId: '1:612115892689:ios:0fc05c5bd0f5fb240f78f0',
    messagingSenderId: '612115892689',
    projectId: 'haksik-e3b46',
    storageBucket: 'haksik-e3b46.appspot.com',
    iosClientId:
        '612115892689-qn4q4pl3i015mm86avutnj2luuhpbp2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyamNyamFlutter',
  );
}
